### ISSUE TITLE
Getting error deploying to google cloud, because the package is not a module

### ISSUE THREAD

**Issue by mike-hogan** [kgajera/stripe-event-types#1]
When I deploy a google cloud function that has this in it:

```
import Stripe from 'stripe';
import "stripe-event-types";
```

I get this error back from google cloud at deploy time:

```
Provided module can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'stripe-event-types'
Require stack:
- /workspace/dist/cjs/paymentIntentPayloadToMutations.js
- /workspace/dist/cjs/index.js
- /workspace/node_modules/@google-cloud/functions-framework/build/src/loader.js
- /workspace/node_modules/@google-cloud/functions-framework/build/src/main.js
```

I'm 99% sure this is because `stripe-event-types` isn't a module i.e. it has no `main` property in `package.json`

What is the recommended way of permitting import of this package as a module?  Thx!

**Comment by kgajera** [comment]
Thanks for reporting this!

My initial thought is that it will be better to include the types using the `reference` directive  instead of an `import` statement:

```ts
/// <reference types="stripe-event-types" />
```

It's better in my opinion because there's really no module that should be included with this. Sure we could create an empty `index.js` file for the module, but why have that extra import when it's not needed.

For reference: https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-

I will do some testing today and update the documentation.

**Comment by kgajera** [comment]
@mike-hogan I did update the examples in the readme to use the `reference` directive. It is a little ugly but the best solution as this library should not be imported in the transpiled code. Let me know if you have any further issues.
